FROM dockerfile/java
# This is the Dockerfile for Elasticsearch, a searchable storage solution used by Orca.
# We are using the (as of this writing) the 1.4 beta version of Elasticsearch, so there
# is no official Docker container.  Elasticsearch needs Java, so start with the
# official Java Image.
MAINTAINER Dan Yoder (dan@pandastrike.com)

#============================================
# INSTALLATION
#============================================

# Pull the Elasticsearch 1.4 (beta) from the Web.
RUN curl https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.0.Beta1.zip > elasticsearch-1.4.0.Beta1.zip
RUN unzip elasticsearch-1.4.0.Beta1.zip -d elasticsearch
RUN rm elasticsearch-1.4.0.Beta1.zip


# For now, there is no need for configuration, so just deploy Elasticsearch.


#============================================
# DEPLOY
#============================================
CMD ./elasticsearch/elasticsearch-1.4.0.Beta1/bin/elasticsearch
